# Generated by Django 3.2.10 on 2022-01-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('TWINT', 'Twint'), ('CREDIT', 'Credit')], default='CASH', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
